header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: '/odom'
poses:
- position:
    x: 0.075
    y: 1
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 2.0
    y: -1.925
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 2.0
    y: -2.075
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 0.075
    y: -4.25
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 3.25
    y: -6.425
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 6.425
    y: -1.5
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 4.5
    y: 3.425
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 4.5
    y: 3.575
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 6.425
    y: 5
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: 0.0
    y: 6.425
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: -6.425
    y: 3.25
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: -4.5
    y: 0.075
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: -4.5
    y: 0.075
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: -4.5
    y: -0.075
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: -6.425
    y: -3.25
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: -3.25
    y: -6.425
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
- position:
    x: -0.075
    y: -1.25
    z: 0.275
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0